package com.dslexample.generateddsl

import static javaposse.jobdsl.dsl.Preconditions.checkNotNullOrEmpty

/**
 *  keep the code normally generated by
 *    <a href="https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL">Automatically Generated
 *    DSL</a>
 */
class RundeckNotificationConfiguration {
    String rundeckInstanceName
    String jobIdName
    Map<String, String> rundeckOptions = [:]
    String nodeFiltersNames = ''
    String tagsNames = ''

    boolean isWaitForRundeckJob
    boolean isFailTheBuild
    boolean isIncludeRundeckLogs
    boolean isTailLog

    static RundeckNotificationConfiguration of(String rundeckTask, Map<String, String> rundeckOptions = [:]) {
        checkNotNullOrEmpty(rundeckTask, 'rundeckTask cannot be null or empty')
        RundeckNotificationConfiguration configuration = new RundeckNotificationConfiguration()
        configuration.setJobIdName(rundeckTask)
        configuration.setRundeckOptions(rundeckOptions)
        return configuration
    }

    private Closure rundeckNotificationDsl = {
        return rundeckNotifier {
            rundeckInstance(rundeckInstanceName ?: 'Default')
            jobId(jobIdName)
            options(rundeckOptions.collect { key, value -> "${key}=${value}" }.join('\n'))
            nodeFilters(nodeFiltersNames)
            tags(tagsNames)
            shouldWaitForRundeckJob(isWaitForRundeckJob)
            shouldFailTheBuild(isFailTheBuild)
            includeRundeckLogs(isIncludeRundeckLogs)
            tailLog(isTailLog)
        }
    }

    Closure getRundeckNotificationDsl() {
        return rundeckNotificationDsl
    }
}
